services:
  db:
    image: mysql:8.0
    container_name: dev-mysql
    environment:
      MYSQL_DATABASE: ecommerceDashboard
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306" # optional, only if you want to connect from host
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      # - db_data:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: password
      DB_NAME: ecommerceDashboard
      PORT: "8080"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db
# volumes:
#   db_data:
